version: '3.1'
services: 
  db: 
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
  angular: # The name of the service
    build: ./angular # Location of our Dockerfile
    volumes: # Volume binding
      - './front_mosquitto_chat:/usr/src/app' 
    ports: 
      - '4200:4200' # Port mapping
    command:
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
networks:
  backend: